# Generated by Django 4.2.30 on 2026-06-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform_id",
                    models.CharField(
                        blank=True,
                        help_text="ID original en la red social (para Fase 2 evitar duplicados)",
                        max_length=200,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("comment", "Comentario"),
                            ("dm", "Mensaje directo"),
                            ("reply", "Respuesta"),
                        ],
                        default="comment",
                        max_length=20,
                    ),
                ),
                (
                    "from_username",
                    models.CharField(help_text="Quien escribió", max_length=120),
                ),
                (
                    "content",
                    models.TextField(help_text="Texto del mensaje o comentario"),
                ),
                (
                    "post_url",
                    models.URLField(
                        blank=True, help_text="URL de la publicación donde ocurrió"
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(help_text="Fecha y hora real del mensaje"),
                ),
                (
                    "fetched_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Cuando lo registramos en ArtistHub",
                    ),
                ),
            ],
            options={
                "verbose_name": "interacción",
                "verbose_name_plural": "interacciones",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sugerencia", "Sugerencia"),
                            ("colaboracion", "Colaboración"),
                            ("cliente", "Cliente potencial"),
                            ("revisar", "Revisar luego"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("revisado", "Revisado"),
                            ("archivado", "Archivado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True, help_text="Lo que el artista quiere recordar"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "nota",
                "verbose_name_plural": "notas",
            },
        ),
        migrations.CreateModel(
            name="SocialAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("tiktok", "TikTok"),
                            ("facebook", "Facebook"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "handle",
                    models.CharField(
                        help_text="@nombre en esa red social", max_length=120
                    ),
                ),
                (
                    "access_token",
                    models.TextField(
                        blank=True, help_text="Token OAuth (se llenará en Fase 2)"
                    ),
                ),
                ("token_expires", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "cuenta social",
                "verbose_name_plural": "cuentas sociales",
                "ordering": ["platform"],
            },
        ),
    ]
