# Generated by Django 4.2.30 on 2026-06-01 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("interactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialaccount",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="interaction",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="note",
                to="interactions.interaction",
            ),
        ),
        migrations.AddField(
            model_name="interaction",
            name="social_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interactions",
                to="interactions.socialaccount",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="socialaccount",
            unique_together={("artist", "platform", "handle")},
        ),
    ]
