# Generated by Django 4.2.30 on 2026-06-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialaccount",
            name="ig_user_id",
            field=models.CharField(
                blank=True,
                help_text="Instagram Business Account ID (para API Graph)",
                max_length=50,
            ),
        ),
    ]
